environmentName: Minecraft
runName: Minecraft-Training-Attempt-6
seed: 1

gradientSteps: 60000
envStepsPerTrainingStep: 4 #batchSize*batchLength/ number
saveMetrics: True        # Saves metrics at replayRatio interval
saveCheckpoints: True
checkpointInterval: 1000
resume: False
checkpointToLoad: 9k
#
episodesBeforeStart: 0
numInteractionEpisodes: 1
numEvaluationEpisodes: 1


dreamer:
  actionRepeat: 1
  batchSize: 24
  batchLength: 24
  imaginationHorizon: 16

  recurrentSize: 8192 #1024*8
  latentLength: 32 #32
  latentClasses: 64 #64
  encodedObsSize: 4096
#  resolution: [256, 448]
#  resolution: [160, 368]
  resolution: [ 64, 64 ]

  actorLR: 0.00004
  criticLR: 0.0001
  worldModelLR: 0.0006
  gradientNormType: 2
  gradientClip: 100
  reconstructionLossCoefficient: 10

  discount: 0.997
  lambda_: 0.95
  freeNats: 1
  betaPrior: 1.0
  betaPosterior: 0.1
  entropyScale: 0.0003

  buffer:
    capacity: 15000 #TODO Bigger buffer in real training
    minecraft:
      scene_size: [20, 16, 20]

  encoder:
    depth: 64
    stride: 2
    kernelSize: 4
    activation: ReLU

  decoder:
    depth: 64
    stride: 2
    kernelSize: 4
    activation: ReLU

  recurrentModel:
    hiddenSize: 1024
    numBlocks: 8
    activation: ReLU

  priorNet:
    hiddenSize: 1024
    numLayers: 2
    activation: ReLU
    uniformMix: 0.01

  posteriorNet:
    hiddenSize: 1024
    numLayers: 2
    activation: ReLU
    uniformMix: 0.01

  reward:
    hiddenSize: 1024
    numLayers: 2
    activation: ReLU

  continuation:
    hiddenSize: 1024
    numLayers: 3
    activation: ReLU

  actor:
    hiddenSize: 1024
    numLayers: 2
    activation: ReLU

  critic:
    hiddenSize: 1024
    numLayers: 3
    activation: ReLU

  minecraft:
    fov: 90
    classes: 236
    scene_size: [20, 16, 20]
    projection_scale: 1
    prediction_head:
      dilations: [1, 2, 3]
      feature_size: 64 #64



folderNames:
  metricsFolder: /content/drive/MyDrive/NaturalDreamer/metrics
  plotsFolder: /content/plots
  checkpointsFolder: /content/drive/MyDrive/NaturalDreamer/checkpoints
  videosFolder: /content/videos
