environmentName: Minecraft
runName: Minecraft-Test-Run
seed: 1

gradientSteps: 60000
replayRatio: 200
saveMetrics: True        # Saves metrics at replayRatio interval
saveCheckpoints: True
checkpointInterval: 500
resume: False #True
checkpointToLoad: 3k
#
episodesBeforeStart: 1
numInteractionEpisodes: 1
numEvaluationEpisodes: 1


dreamer:
  actionRepeat: 3
  batchSize: 3
  batchLength: 32
  imaginationHorizon: 196

  recurrentSize: 512 #1024*8
  latentLength: 16 #32
  latentClasses: 16 #64
  encodedObsSize: 1024
#  resolution: [368, 640]
#  resolution: [160, 368]
  resolution: [ 64, 96 ]

  actorLR: 0.00004
  criticLR: 0.0001
  worldModelLR: 0.0002
  gradientNormType: 2
  gradientClip: 100

  discount: 0.997
  lambda_: 0.95
  freeNats: 1
  betaPrior: 1.0
  betaPosterior: 0.1
  entropyScale: 0.0003

  buffer:
    capacity: 5000 #TODO Bigger buffer in real training
    minecraft:
      scene_size: [20, 16, 20]

  encoder:
    depth: 16
    stride: 2
    kernelSize: 4
    activation: ReLU #TODO activation = RElU

  decoder:
    depth: 16
    stride: 2
    kernelSize: 4
    activation: ReLU

  recurrentModel:
    hiddenSize: 200
    activation: ReLU

  priorNet:
    hiddenSize: 200
    numLayers: 2
    activation: ReLU
    uniformMix: 0.01

  posteriorNet:
    hiddenSize: 200
    numLayers: 2
    activation: ReLU
    uniformMix: 0.01

  reward:
    hiddenSize: 400
    numLayers: 2
    activation: ReLU

  continuation:
    hiddenSize: 400
    numLayers: 3
    activation: ReLU

  actor:
    hiddenSize: 400
    numLayers: 2
    activation: ReLU

  critic:
    hiddenSize: 400
    numLayers: 3
    activation: ReLU

  minecraft:
    fov: 90
    classes: 236
    scene_size: [20, 16, 20]
    projection_scale: 1
    prediction_head:
      dilations: [1, 2, 3]
      feature_size: 64 #64



folderNames:
  metricsFolder: metrics
  plotsFolder: plots
  checkpointsFolder: checkpoints
  videosFolder: videos


