services:
  malmo_dreamer:
    build: .
    shm_size: "4gb"
    ports:
      - "10000:10000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
